version: '3.8'

services:
  student-app:
    image: student-service:latest
    build:
      context: .
    ports:
      - "9090:9090"
      - "9000:9000"
    restart: always
    environment:
      SERVER_PORT: 9090
      GRAPHQL_CLIENT_URL: http://localhost:8080

volumes:
  postgres-data: